### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by caophuong2012** [tomcao/english#1]
Please follow the following description to make a short presentation.

[Hello class.docx](https://github.com/tomcao/english/files/363197/Hello.class.docx)

**P/S:** You should spend about 10 mins on your speech.

**Comment by tomcaovn** [comment]
Hi teacher, I'm Phuong and this is my script about this presenation.
[Hello.class.docx](https://github.com/tomcao/english/files/363210/Hello.class.docx)
Thanks!
